class PokemonTypesDamageRelation {
  static final typesDamageRelation = [
    {
      "type": "normal",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 2, "type": "fighting"},
        {"damage_factor": 1, "type": "flying"},
        {"damage_factor": 1, "type": "poison"},
        {"damage_factor": 1, "type": "ground"},
        {"damage_factor": 1, "type": "rock"},
        {"damage_factor": 1, "type": "bug"},
        {"damage_factor": 0, "type": "ghost"},
        {"damage_factor": 1, "type": "steel"},
        {"damage_factor": 1, "type": "fire"},
        {"damage_factor": 1, "type": "water"},
        {"damage_factor": 1, "type": "grass"},
        {"damage_factor": 1, "type": "electric"},
        {"damage_factor": 1, "type": "psychic"},
        {"damage_factor": 1, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 1, "type": "dark"},
        {"damage_factor": 1, "type": "fairy"}
      ]
    },
    {
      "type": "fighting",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 1, "type": "fighting"},
        {"damage_factor": 2, "type": "flying"},
        {"damage_factor": 1, "type": "poison"},
        {"damage_factor": 1, "type": "ground"},
        {"damage_factor": 0.5, "type": "rock"},
        {"damage_factor": 0.5, "type": "bug"},
        {"damage_factor": 1, "type": "ghost"},
        {"damage_factor": 1, "type": "steel"},
        {"damage_factor": 1, "type": "fire"},
        {"damage_factor": 1, "type": "water"},
        {"damage_factor": 1, "type": "grass"},
        {"damage_factor": 1, "type": "electric"},
        {"damage_factor": 2, "type": "psychic"},
        {"damage_factor": 1, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 0.5, "type": "dark"},
        {"damage_factor": 2, "type": "fairy"}
      ]
    },
    {
      "type": "flying",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 0.5, "type": "fighting"},
        {"damage_factor": 1, "type": "flying"},
        {"damage_factor": 1, "type": "poison"},
        {"damage_factor": 0, "type": "ground"},
        {"damage_factor": 2, "type": "rock"},
        {"damage_factor": 0.5, "type": "bug"},
        {"damage_factor": 1, "type": "ghost"},
        {"damage_factor": 1, "type": "steel"},
        {"damage_factor": 1, "type": "fire"},
        {"damage_factor": 1, "type": "water"},
        {"damage_factor": 0.5, "type": "grass"},
        {"damage_factor": 2, "type": "electric"},
        {"damage_factor": 1, "type": "psychic"},
        {"damage_factor": 2, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 1, "type": "dark"},
        {"damage_factor": 1, "type": "fairy"}
      ]
    },
    {
      "type": "poison",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 0.5, "type": "fighting"},
        {"damage_factor": 1, "type": "flying"},
        {"damage_factor": 0.5, "type": "poison"},
        {"damage_factor": 2, "type": "ground"},
        {"damage_factor": 1, "type": "rock"},
        {"damage_factor": 0.5, "type": "bug"},
        {"damage_factor": 1, "type": "ghost"},
        {"damage_factor": 1, "type": "steel"},
        {"damage_factor": 1, "type": "fire"},
        {"damage_factor": 1, "type": "water"},
        {"damage_factor": 0.5, "type": "grass"},
        {"damage_factor": 1, "type": "electric"},
        {"damage_factor": 2, "type": "psychic"},
        {"damage_factor": 1, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 1, "type": "dark"},
        {"damage_factor": 0.5, "type": "fairy"}
      ]
    },
    {
      "type": "ground",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 1, "type": "fighting"},
        {"damage_factor": 1, "type": "flying"},
        {"damage_factor": 0.5, "type": "poison"},
        {"damage_factor": 1, "type": "ground"},
        {"damage_factor": 0.5, "type": "rock"},
        {"damage_factor": 1, "type": "bug"},
        {"damage_factor": 1, "type": "ghost"},
        {"damage_factor": 1, "type": "steel"},
        {"damage_factor": 1, "type": "fire"},
        {"damage_factor": 2, "type": "water"},
        {"damage_factor": 2, "type": "grass"},
        {"damage_factor": 0, "type": "electric"},
        {"damage_factor": 1, "type": "psychic"},
        {"damage_factor": 2, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 1, "type": "dark"},
        {"damage_factor": 1, "type": "fairy"}
      ]
    },
    {
      "type": "rock",
      "damage_relation": [
        {"damage_factor": 0.5, "type": "normal"},
        {"damage_factor": 2, "type": "fighting"},
        {"damage_factor": 0.5, "type": "flying"},
        {"damage_factor": 0.5, "type": "poison"},
        {"damage_factor": 2, "type": "ground"},
        {"damage_factor": 1, "type": "rock"},
        {"damage_factor": 1, "type": "bug"},
        {"damage_factor": 1, "type": "ghost"},
        {"damage_factor": 2, "type": "steel"},
        {"damage_factor": 0.5, "type": "fire"},
        {"damage_factor": 2, "type": "water"},
        {"damage_factor": 2, "type": "grass"},
        {"damage_factor": 1, "type": "electric"},
        {"damage_factor": 1, "type": "psychic"},
        {"damage_factor": 1, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 1, "type": "dark"},
        {"damage_factor": 1, "type": "fairy"}
      ]
    },
    {
      "type": "bug",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 0.5, "type": "fighting"},
        {"damage_factor": 2, "type": "flying"},
        {"damage_factor": 1, "type": "poison"},
        {"damage_factor": 0.5, "type": "ground"},
        {"damage_factor": 2, "type": "rock"},
        {"damage_factor": 1, "type": "bug"},
        {"damage_factor": 1, "type": "ghost"},
        {"damage_factor": 1, "type": "steel"},
        {"damage_factor": 2, "type": "fire"},
        {"damage_factor": 1, "type": "water"},
        {"damage_factor": 0.5, "type": "grass"},
        {"damage_factor": 1, "type": "electric"},
        {"damage_factor": 1, "type": "psychic"},
        {"damage_factor": 1, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 1, "type": "dark"},
        {"damage_factor": 1, "type": "fairy"}
      ]
    },
    {
      "type": "ghost",
      "damage_relation": [
        {"damage_factor": 0, "type": "normal"},
        {"damage_factor": 0, "type": "fighting"},
        {"damage_factor": 1, "type": "flying"},
        {"damage_factor": 0.5, "type": "poison"},
        {"damage_factor": 1, "type": "ground"},
        {"damage_factor": 1, "type": "rock"},
        {"damage_factor": 0.5, "type": "bug"},
        {"damage_factor": 2, "type": "ghost"},
        {"damage_factor": 1, "type": "steel"},
        {"damage_factor": 1, "type": "fire"},
        {"damage_factor": 1, "type": "water"},
        {"damage_factor": 1, "type": "grass"},
        {"damage_factor": 1, "type": "electric"},
        {"damage_factor": 1, "type": "psychic"},
        {"damage_factor": 1, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 2, "type": "dark"},
        {"damage_factor": 1, "type": "fairy"}
      ]
    },
    {
      "type": "steel",
      "damage_relation": [
        {"damage_factor": 0.5, "type": "normal"},
        {"damage_factor": 2, "type": "fighting"},
        {"damage_factor": 0.5, "type": "flying"},
        {"damage_factor": 0, "type": "poison"},
        {"damage_factor": 2, "type": "ground"},
        {"damage_factor": 0.5, "type": "rock"},
        {"damage_factor": 0.5, "type": "bug"},
        {"damage_factor": 1, "type": "ghost"},
        {"damage_factor": 0.5, "type": "steel"},
        {"damage_factor": 2, "type": "fire"},
        {"damage_factor": 1, "type": "water"},
        {"damage_factor": 0.5, "type": "grass"},
        {"damage_factor": 1, "type": "electric"},
        {"damage_factor": 0.5, "type": "psychic"},
        {"damage_factor": 0.5, "type": "ice"},
        {"damage_factor": 0.5, "type": "dragon"},
        {"damage_factor": 1, "type": "dark"},
        {"damage_factor": 0.5, "type": "fairy"}
      ]
    },
    {
      "type": "fire",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 1, "type": "fighting"},
        {"damage_factor": 1, "type": "flying"},
        {"damage_factor": 1, "type": "poison"},
        {"damage_factor": 2, "type": "ground"},
        {"damage_factor": 2, "type": "rock"},
        {"damage_factor": 0.5, "type": "bug"},
        {"damage_factor": 1, "type": "ghost"},
        {"damage_factor": 0.5, "type": "steel"},
        {"damage_factor": 0.5, "type": "fire"},
        {"damage_factor": 2, "type": "water"},
        {"damage_factor": 0.5, "type": "grass"},
        {"damage_factor": 1, "type": "electric"},
        {"damage_factor": 1, "type": "psychic"},
        {"damage_factor": 0.5, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 1, "type": "dark"},
        {"damage_factor": 0.5, "type": "fairy"}
      ]
    },
    {
      "type": "water",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 1, "type": "fighting"},
        {"damage_factor": 1, "type": "flying"},
        {"damage_factor": 1, "type": "poison"},
        {"damage_factor": 1, "type": "ground"},
        {"damage_factor": 1, "type": "rock"},
        {"damage_factor": 1, "type": "bug"},
        {"damage_factor": 1, "type": "ghost"},
        {"damage_factor": 0.5, "type": "steel"},
        {"damage_factor": 0.5, "type": "fire"},
        {"damage_factor": 0.5, "type": "water"},
        {"damage_factor": 2, "type": "grass"},
        {"damage_factor": 2, "type": "electric"},
        {"damage_factor": 1, "type": "psychic"},
        {"damage_factor": 0.5, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 1, "type": "dark"},
        {"damage_factor": 1, "type": "fairy"}
      ]
    },
    {
      "type": "grass",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 1, "type": "fighting"},
        {"damage_factor": 2, "type": "flying"},
        {"damage_factor": 2, "type": "poison"},
        {"damage_factor": 0.5, "type": "ground"},
        {"damage_factor": 1, "type": "rock"},
        {"damage_factor": 2, "type": "bug"},
        {"damage_factor": 1, "type": "ghost"},
        {"damage_factor": 1, "type": "steel"},
        {"damage_factor": 2, "type": "fire"},
        {"damage_factor": 0.5, "type": "water"},
        {"damage_factor": 0.5, "type": "grass"},
        {"damage_factor": 0.5, "type": "electric"},
        {"damage_factor": 1, "type": "psychic"},
        {"damage_factor": 2, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 1, "type": "dark"},
        {"damage_factor": 1, "type": "fairy"}
      ]
    },
    {
      "type": "electric",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 1, "type": "fighting"},
        {"damage_factor": 0.5, "type": "flying"},
        {"damage_factor": 1, "type": "poison"},
        {"damage_factor": 2, "type": "ground"},
        {"damage_factor": 1, "type": "rock"},
        {"damage_factor": 1, "type": "bug"},
        {"damage_factor": 1, "type": "ghost"},
        {"damage_factor": 0.5, "type": "steel"},
        {"damage_factor": 1, "type": "fire"},
        {"damage_factor": 1, "type": "water"},
        {"damage_factor": 1, "type": "grass"},
        {"damage_factor": 0.5, "type": "electric"},
        {"damage_factor": 1, "type": "psychic"},
        {"damage_factor": 1, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 1, "type": "dark"},
        {"damage_factor": 1, "type": "fairy"}
      ]
    },
    {
      "type": "psychic",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 0.5, "type": "fighting"},
        {"damage_factor": 1, "type": "flying"},
        {"damage_factor": 1, "type": "poison"},
        {"damage_factor": 1, "type": "ground"},
        {"damage_factor": 1, "type": "rock"},
        {"damage_factor": 2, "type": "bug"},
        {"damage_factor": 2, "type": "ghost"},
        {"damage_factor": 1, "type": "steel"},
        {"damage_factor": 1, "type": "fire"},
        {"damage_factor": 1, "type": "water"},
        {"damage_factor": 1, "type": "grass"},
        {"damage_factor": 1, "type": "electric"},
        {"damage_factor": 0.5, "type": "psychic"},
        {"damage_factor": 1, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 2, "type": "dark"},
        {"damage_factor": 1, "type": "fairy"}
      ]
    },
    {
      "type": "ice",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 2, "type": "fighting"},
        {"damage_factor": 1, "type": "flying"},
        {"damage_factor": 1, "type": "poison"},
        {"damage_factor": 1, "type": "ground"},
        {"damage_factor": 2, "type": "rock"},
        {"damage_factor": 1, "type": "bug"},
        {"damage_factor": 1, "type": "ghost"},
        {"damage_factor": 2, "type": "steel"},
        {"damage_factor": 2, "type": "fire"},
        {"damage_factor": 1, "type": "water"},
        {"damage_factor": 1, "type": "grass"},
        {"damage_factor": 1, "type": "electric"},
        {"damage_factor": 1, "type": "psychic"},
        {"damage_factor": 0.5, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 1, "type": "dark"},
        {"damage_factor": 1, "type": "fairy"}
      ]
    },
    {
      "type": "dragon",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 1, "type": "fighting"},
        {"damage_factor": 1, "type": "flying"},
        {"damage_factor": 1, "type": "poison"},
        {"damage_factor": 1, "type": "ground"},
        {"damage_factor": 1, "type": "rock"},
        {"damage_factor": 1, "type": "bug"},
        {"damage_factor": 1, "type": "ghost"},
        {"damage_factor": 1, "type": "steel"},
        {"damage_factor": 0.5, "type": "fire"},
        {"damage_factor": 0.5, "type": "water"},
        {"damage_factor": 0.5, "type": "grass"},
        {"damage_factor": 0.5, "type": "electric"},
        {"damage_factor": 1, "type": "psychic"},
        {"damage_factor": 2, "type": "ice"},
        {"damage_factor": 2, "type": "dragon"},
        {"damage_factor": 1, "type": "dark"},
        {"damage_factor": 2, "type": "fairy"}
      ]
    },
    {
      "type": "dark",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 2, "type": "fighting"},
        {"damage_factor": 1, "type": "flying"},
        {"damage_factor": 1, "type": "poison"},
        {"damage_factor": 1, "type": "ground"},
        {"damage_factor": 1, "type": "rock"},
        {"damage_factor": 2, "type": "bug"},
        {"damage_factor": 0.5, "type": "ghost"},
        {"damage_factor": 1, "type": "steel"},
        {"damage_factor": 1, "type": "fire"},
        {"damage_factor": 1, "type": "water"},
        {"damage_factor": 1, "type": "grass"},
        {"damage_factor": 1, "type": "electric"},
        {"damage_factor": 0, "type": "psychic"},
        {"damage_factor": 1, "type": "ice"},
        {"damage_factor": 1, "type": "dragon"},
        {"damage_factor": 0.5, "type": "dark"},
        {"damage_factor": 2, "type": "fairy"}
      ]
    },
    {
      "type": "fairy",
      "damage_relation": [
        {"damage_factor": 1, "type": "normal"},
        {"damage_factor": 0.5, "type": "fighting"},
        {"damage_factor": 1, "type": "flying"},
        {"damage_factor": 2, "type": "poison"},
        {"damage_factor": 1, "type": "ground"},
        {"damage_factor": 1, "type": "rock"},
        {"damage_factor": 0.5, "type": "bug"},
        {"damage_factor": 1, "type": "ghost"},
        {"damage_factor": 2, "type": "steel"},
        {"damage_factor": 1, "type": "fire"},
        {"damage_factor": 1, "type": "water"},
        {"damage_factor": 1, "type": "grass"},
        {"damage_factor": 1, "type": "electric"},
        {"damage_factor": 1, "type": "psychic"},
        {"damage_factor": 1, "type": "ice"},
        {"damage_factor": 0, "type": "dragon"},
        {"damage_factor": 0.5, "type": "dark"},
        {"damage_factor": 1, "type": "fairy"}
      ]
    }
  ];
}
